-- MySQL Script generated by MySQL Workbench
-- Fri 16 Oct 2020 01:07:37 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SupplyChain
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SupplyChain
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SupplyChain` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `SupplyChain` ;

-- -----------------------------------------------------
-- Table `SupplyChain`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupplyChain`.`Store` (
  `id` INT NOT NULL,
  `name_branch` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SupplyChain`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupplyChain`.`Employee` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `store_id` INT NOT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `store_id` (`store_id` ASC) VISIBLE,
  CONSTRAINT `Employee_ibfk_1`
    FOREIGN KEY (`store_id`)
    REFERENCES `SupplyChain`.`Store` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SupplyChain`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupplyChain`.`Supplier` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SupplyChain`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupplyChain`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `category_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `unit_price` INT NULL DEFAULT NULL,
  `quantity_unit` INT NULL DEFAULT NULL,
  `num_in_stock` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `supplier_id` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `Products_ibfk_1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `SupplyChain`.`Supplier` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SupplyChain`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupplyChain`.`Orders` (
  `id` INT NOT NULL,
  `order_status` INT NULL DEFAULT NULL,
  `due_order` DATETIME NULL DEFAULT NULL,
  `made_by` INT NOT NULL,
  `detail_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `detail_id` (`detail_id` ASC) VISIBLE,
  INDEX `made_by` (`made_by` ASC) VISIBLE,
  CONSTRAINT `Orders_ibfk_1`
    FOREIGN KEY (`detail_id`)
    REFERENCES `SupplyChain`.`Order_details` (`id`),
  CONSTRAINT `Orders_ibfk_2`
    FOREIGN KEY (`made_by`)
    REFERENCES `SupplyChain`.`Store` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SupplyChain`.`Order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SupplyChain`.`Order_details` (
  `id` INT NOT NULL,
  `total_items` INT NULL DEFAULT NULL,
  `details` VARCHAR(45) NULL DEFAULT NULL,
  `product_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `Order_details_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `SupplyChain`.`Products` (`id`),
  CONSTRAINT `Order_details_ibfk_2`
    FOREIGN KEY (`order_id`)
    REFERENCES `SupplyChain`.`Orders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
